name: mockup
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5
  intl: ^0.18.0
  kiosk_mode: 
  neon_widgets: ^2.0.0
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
